# Generated by Django 4.1.5 on 2023-02-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=6),
        ),
    ]
